// import { Inter } from 'next/font/google'
// // import '@/globals.css'




// // import Navbar from '@sh_components/navbar/Navbar'
// // import Sidebar from '@/app/sh_components/sidebar/Sidebar'
// // import Footer from '@/app/sh_components/footer/Footer'
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className='flex h-screen overflow-hidden'>
//           <Sidebar />
//           <div className='relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden'>
//             <Navbar />
//             <main>
//               <div className='mx-4 max-w-screen-2xl p-4 md:p-6 2xl:p-10'>
//                 {children}

//               </div>
//             </main>
//             <Footer />

//           </div>
//         </div>

//       </body>
//     </html>
//   )
// }
// import { Inter } from 'next/font/google'
// import '../globals.css'
// // const inter = Inter({ subsets: ['latin'] })
// const Stakelayout = ({children}) => {
//   return (
//     <html lang="en">
//       <body>
//         <div className='flex h-screen overflow-hidden'>
//           <Sidebar />
//           <div className='relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden'>
//             <Navbar />
//             <main>
//               <div className='mx-4 max-w-screen-2xl p-4 md:p-6 2xl:p-10'>
//                 {children}

//               </div>
//             </main>
//             <Footer />

//           </div>
//         </div>

//       </body>
//     </html>
//   )
// }

// export default Stakelayout
// import Navbar from '../../dash_components/dashboard/navbar/Navbar'

import Navbar from '@/dash_components/navbar/Navbar'
import Sidebar from '@/dash_components/sidebar/Sidebar'
import Footer from '@/dash_components/footer/Footer'

const Layout = ({children}) => {
  return (
    <div className='flex h-screen overflow-hidden'>
           <Sidebar />
           <div className='relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden'>
             <Navbar />
             <main>
               <div className='mx-4 max-w-screen-2xl p-4 md:p-6 2xl:p-10'>
                 {children}

               </div>
             </main>
             <Footer />

           </div>
         </div>
  )
}

export default Layout
